### PR TITLE
WLED discovery

### PR DESCRIPTION
**Pull request by netmindz**

### CODE REVIEW

**Comment by netmindz** [comment]
Should really be populating an collection of unique ips, but can't find `Set` for Arduino, don't really want to write from scratch

**Comment by ewowi** [comment]
Can it be used to discover also StarMod modules? How does it know what makes it a WLED device?

Could it we make it a module with UI, so the UI shows other modules in the network? 

Is it permanently polling or does it need to be refreshed?

**Comment by netmindz** [comment]
It's listening for the UDP announcements made by WLED

We can write a similar mod that sends out UDP announcements and listens for our own

As for UI, not looked at any of that code.

Probably more useful to update the DDP and ArtNet to have UI to select the WLED instance as target than just having a panel that lists WLED info, but doesn't let you do anything with it

**Comment by ewoudwijma** [comment]
Agree with UI selecting from a list of instances discovered!
Is it idea you make the usermod showing instances (WLED and StarMod) and after that I make the  ui selecting them?

**Comment by netmindz** [comment]
This mod just provides the data. We then create a new branch for you to create the ArtNet and DDP UI was what I was thinking

**Pull request merged**
