### PR TITLE
Add platformio integration for bundling web asset files before build

### PR DESCRIPTION
**Pull request by aaronaverill**
This pull request creates a new entry in platformio.ini extra_scripts to bundle up web resources before the build. The script also updates node packages if needed.

**Rationale**
The current scheme (borrowed from WLED?) requires an external manual step to build the bundled web files that get compiled into PROGMEM. This has some drawbacks
- increases friction for new developers joining (you need to rtfm to learn the build process, instead of clicking "build")
- if the manual bundle step is skipped before a build the web assets get out of sync with what is build and uploaded
- storing the bundled .h file in source control violates the DRY principle: there should only be one source of truth for the web files - the original source code

**New Requirements**
This requires that any developer of Star[*] have node installed in addition to platformio. This doesn't feel like an onerous requirement for tech work in 2024.

### CODE REVIEW

**Comment by ewoudwijma** [comment]
Thx @aaronaverill , looks pretty straightforward , asking @netmindz  to review as he also made scripts for Star

**Review by netmindz — APPROVED** [review]

**Comment by netmindz** [comment]
Good change. I'd actually made a similar change to WLED-MM to build the .h files automatically recently

**Comment by ewowi** [comment]
Small question: is it possible to check if npm is already installed before executing env.Execute("npm install")

As it might speedup compiling by a second or so ;-) 
(I compile a lot ;-) )

**Comment by netmindz** [comment]
The script used used in WLED I think only runs that build of the html files have been changed

**Comment by netmindz** [comment]
npm ci 

Might also be faster than npm install

**Comment by ewowi** [comment]
Moving the discord discussion here...

**Comment by ewowi** [comment]
@aaronaverill said on July 21:

Background:

I made  a pull request that was merged by ewowi which packages up the web code as a pre-build step before the C++ code is built. This pre-build step requires node to be installed. I mentioned this in the PR as a new requirement for development, but that it seems ok in 2024 since folks have to install other tools like vscode.

This will long term speed up the ability to code new web features quickly with less steps by the UI coders.

I wasn't sure how to add install instructions to the docs if there even are any docs on such a young project. Probably that should be filed as an issue in the project. I'm happy to write up the docs if folks tell me where to put it. 🙂

**Comment by ewowi** [comment]
@spiro-c said on July 21:

why dont just check if node exist and can just give error to install node if there is changes to ui .... and if exist will execute the node buid of the `.h` files
```py
import shutil

path = shutil.which("node") 

if path is None:
    print("no executable found for command 'node'")
else:
    print(f"path to executable 'node': {path}")
```

see https://github.com/ewowi/StarBase/pull/57

**Comment by ewowi** [comment]
@brandon502 said on July 22:

@ewowi wanted me to post this here. When I compile, html_ui.h is modified and breaks the UI for me. Commenting out `pre:tools/webbundle.py` seems to prevent this from happening.

image

image

**Comment by ewowi** [comment]
@flavourdynamics said on July 22:

Confirming that compilation makes similar changes and garbles the webpage.

image

**Comment by ewowi** [comment]
@ewowi July 22:

Import('env')
import glob
import os

if not os.path.isdir('node_modules'):
  env.Execute("npm ci")

if not os.path.exists('wled00/html_ui.h'):
  env.Execute("npm run build")

latest_source = max(glob.glob('wled00/data/*.htm'), key=os.path.getmtime)
latest_export = max(glob.glob('wled00/html_*.h'), key=os.path.getmtime)

if os.path.getmtime(latest_source) > os.path.getmtime(latest_export):
  env.Execute("npm run build")

**Comment by ewowi** [comment]
@spiro-c on July 22:

The npm build is just script defined in package.json https://github.com/MoonModules/WLED/blob/f3e89d070bc19329021dd737849e8e056257a7dd/package.json#L11

**Comment by ewowi** [comment]
@aaronaverill on July 23:

I believe those characters are emoji that have not been encoded incorrectly

https://www.compart.com/en/unicode/U+1F319

**Comment by ewowi** [comment]
@ewowi July 23:

I added the code of WLED (MM) into StarBase and merged it into StarLight: 

https://github.com/ewowi/StarBase/commit/7786bbfc239c28e23e974a1fe6a90909d84f3e12

I added it in the main branch, this will run things only if needed, so in case you do a fresh check out from github it should not generate new html.
Could you check if this is the case, and if so, as no new generation of html, you don't get garbage in the UI?

Update: removed html_*.h files from the gitignore as they need to be in the github repo. In latest main. So now it should work
(This is temporary until the garbage html is fixed)

**Comment by ewowi** [comment]
@ewowi July 24:

Dear all people in this thread: This has become a serious topic 😉 . <@460108453805817874> caused this by automating the html building so the issue became apparent, but the issue was there also if somebody manually ran this process. Luckily @aaronaverill  also brought Live Server under our attention, which allows us to run html directly from VSCode. Really save timing ! I added that to StarBase and StarLight
I made a description how to get this running here: 
https://ewowi.github.io/StarDocs/StarBase/Development/#live-server
and also on that page a description of html building / compression

So there is bad news, there is good news, but bottom line the html compression problem has not been solved yet 😉 But the Live Server might be a tool to see if the emoji work fine there (for me it does).

I don't want to give all of you tasks, but in case you love this issue so much 😜 :
- @brandon502 you could maybe try the live server and see if the emoji are fine there (in that case the npm build process is the possible cause ???)
- @spiro-c  could review the text I wrote in above link? I have limited knowledge of this npm building process, so maybe I didn't wrote everything correctly. Fork and PR text changes if you have them is the easiest, but whatever is easy for you. (I also used WLED style in the webbundle.py, if you feel the execute command you use is better / or any improvement, you can also PR that
- @flavourdynamics after that you can maybe review the whole development page, as it's far from top notch documentation yet 😉
- @aaronaverill can just sitback and have a laugh about the troubles he caused 😉

**Comment by ewowi** [comment]
@aaronaverill July 24

thanks for the tag 😂 you can quickly fix this by writing your HTML in ascii with escape codes so it doesn't depend on character encoding anywhere in the toolchain. Voila. done.
The issue you might be hitting is that the code minifier you use doesn't properly handle file encoding. You might also look at the BOM of the file you saved this in. But it's an unreliable solution. The correct approach is to use HTML encoded characters for unicode emoji
You may also just be hitting a bug in the minifier, or even in node, which could be a frustrating and very resource intensive thing to chase down, especially when you have a simple solution to use ascii encoded characters.
Some tools such as Notepad++ (on Windows) can give you the file encoding accurately including whether there is a BOM at the start. This could be a source of difference between mac/windows

**Comment by ewowi** [comment]
@ewowi July 24

Haha you are welcome 😆, I learned these are called html entities (https://www.w3schools.com/html/html_entities.asp)
But don’t you think as a modern code promotor that this is so old fashioned ? 
And it works in WLED and works on Mac so I want to pinpoint the problem why it isn’t working in windows/Star …

**Comment by ewowi** [comment]
@flavourdynamics

If you installed the MSI it might be a path issue. It's been awhile since I installed node and I can't remember if it requires manually setting the environment path and/or a reboot.
https://nodejs.org/en/download/package-manager
[Node.js — Download Node.js®](https://nodejs.org/en/download/package-manager)
Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine.
Image
This devops update will also allow newer tools which reduce the memory footprint on the chip for the web components, more space for tools and animations, faster.

**Pull request merged**
